import { describe,it,expect } from 'vitest';
import { JournalProjection } from '../src/adapters/journal';
import { diagnostics } from '../src/core/connections';
import { initialState,reduce } from '../src/core/reducer';
import { ROSTER } from '../src/core/config';
import { displayStatus,STALE_AFTER_MS } from '../src/core/selectors';
const at=1_000_000;
const observation=(workerId='uditus.creator')=>({version:1,mode:'live',cursor:1,eventId:'e1',source:'armis-setup-runtime',type:'worker.idle',occurredAt:at,businessId:'uditus',workerId,taskId:null,attemptId:null,sessionId:null,mandateId:null,data:{}});
describe('installed named SSE projection',()=>{
 it('keeps declared identities separate; quiet heartbeats verify continuity without manufacturing work',()=>{const p=new JournalProjection();const result=p.decode('snapshot',JSON.stringify({version:1,mode:'live',epoch:'epoch-1',cursor:1,observations:[observation()]}),at);expect(result.type).toBe('snapshot');if(result.type==='snapshot'){expect(result.snapshot.workers).toHaveLength(29);expect(result.snapshot.statuses[0]?.state).toBe('idle');}expect(p.decode('heartbeat',JSON.stringify({version:1,epoch:'epoch-1',cursor:1}),at).type).toBe('heartbeat');expect(()=>p.decode('events',JSON.stringify({version:1,epoch:'epoch-1',cursor:2,previousCursor:0,observations:[]}),at)).toThrow(/continuity/);});
 it('never aliases runtime shared roles to declared executives and rejects foreign-company binding',()=>{const p=new JournalProjection();const result=p.decode('snapshot',JSON.stringify({version:1,mode:'live',epoch:'epoch-1',cursor:1,observations:[{...observation('armis.auditor'),businessId:'armis'}]}),at);if(result.type==='snapshot')expect(result.snapshot.statuses).toHaveLength(0);expect(()=>p.decode('snapshot',JSON.stringify({version:1,mode:'live',epoch:'epoch-2',cursor:1,observations:[observation('etsy.creator')]}),at)).toThrow(/mismatch/);});
 it('projects explicit capacity without fabricating scope kind or provider entitlement',()=>{diagnostics.reset();const p=new JournalProjection();const value={...observation(),workerId:null,businessId:'armis',type:'capacity.limited',data:{capacityPoolId:'openai-plan',provider:'openai',remaining:20,total:100,resetAt:at+10000,observedAt:at,unit:'requests',quotaProvenance:'observed'}};const result=p.decode('snapshot',JSON.stringify({version:1,mode:'live',epoch:'epoch-1',cursor:1,observations:[value]}),at);if(result.type==='snapshot'){expect(result.snapshot.capacity[0]?.scope.kind).toBe('unknown');expect(result.snapshot.capacity[0]?.remaining).toMatchObject({value:20,provenance:'provider_reported'});expect(result.snapshot.capacity[0]?.quotaWindows?.[0]?.total.value).toBe(100);}const unknown=p.decode('snapshot',JSON.stringify({version:1,mode:'live',epoch:'epoch-2',cursor:1,observations:[{...value,data:{...value.data,quotaProvenance:'unknown'}}]}),at);if(unknown.type==='snapshot')expect(unknown.snapshot.capacity[0]?.remaining.value).toBeNull();});
 it('retains unbound and unsupported source evidence and usage metadata with bounded projection counts',()=>{diagnostics.reset();const p=new JournalProjection();p.decode('snapshot',JSON.stringify({version:1,mode:'live',epoch:'epoch-1',cursor:2,observations:[{...observation('armis.auditor'),businessId:'armis',data:{inputTokens:42}},{...observation(),cursor:2,eventId:'artifact2',type:'artifact.handed-off',data:{artifactId:'report2'}}]}),at);const d=diagnostics.get();expect(d.unboundObservations).toBe(1);expect(d.unmappedObservations).toBe(2);expect(d.journalEvidence[0]).toMatchObject({role:'armis.auditor',inputTokens:42});expect(d.journalEvidence[1]?.artifactId).toBe('report2');});
 it('model metadata does not revive a stale active worker',()=>{const worker=ROSTER.find(w=>w.id==='uditus.creator')!;let state=initialState(ROSTER,'connected',at);state=reduce(state,{kind:'event',event:{id:'active',type:'worker.state',sourceTs:at,receivedTs:at,businessId:'uditus',workerId:worker.id,payload:{state:'active'}}});const now=at+STALE_AFTER_MS+1000;state=reduce(state,{kind:'event',event:{id:'model',type:'worker.provider',sourceTs:now,receivedTs:now,businessId:'uditus',workerId:worker.id,payload:{provider:{provider:'openai',model:'observed-model',modelProvenance:'locally_measured'}}}});state=reduce(state,{kind:'tick',now});expect(displayStatus(state,worker).state).toBe('unknown');expect(state.statuses[worker.id]?.lastObservedAt).toBe(at);expect(state.statuses[worker.id]?.provider?.model).toBe('observed-model');});
 it('derived event IDs are stable regardless of preceding journal records',()=>{const source=observation();const full=new JournalProjection().decode('snapshot',JSON.stringify({version:1,mode:'live',epoch:'epoch',cursor:2,observations:[{...source,eventId:'earlier'}, {...source,eventId:'later',cursor:2}]}),at);const p=new JournalProjection();p.decode('snapshot',JSON.stringify({version:1,mode:'live',epoch:'epoch',cursor:1,observations:[{...source,eventId:'earlier'}]}),at);const delta=p.decode('events',JSON.stringify({version:1,epoch:'epoch',cursor:2,previousCursor:1,observations:[{...source,eventId:'later',cursor:2}]}),at);if(full.type==='snapshot'&&delta.type==='events')expect(delta.events[0]?.id).toBe(full.snapshot.timeline?.find(t=>t.eventId.startsWith('later:'))?.eventId);});
});
