import test from 'node:test';
import assert from 'node:assert/strict';
import { switchViewer, rollbackViewer, renderRecoverySwitch, verifyRecoveryBinding } from './city-v2-deploy.mjs';
const id={version:2,contract:'measured-read-only-recovery-v1',revision:'a'.repeat(40),branch:'fixture',dirty:true,builtAt:1,sourceHash:'b'.repeat(64),assetHash:'c'.repeat(64),buildHash:'d'.repeat(64)};
function fixture(){const calls=[];const plan={root:'/candidate',previousRoot:'/original',recoveryRoot:'/measured',node:'/node',policyPath:'/original/policy.json',recoveryContent:renderRecoverySwitch({root:'/measured',node:'/node',policyPath:'/original/policy.json'}),recoveryIdentity:{...id},recoveryOrigin:'http://127.0.0.1:49123',origin:'http://127.0.0.1:4173',identity:{revision:id.revision,sourceHash:id.sourceHash,buildHash:id.buildHash},content:'candidate',ownPrevious:null};const adapter={capture:()=>calls.push('capture'),identity:()=>plan.identity,recoveryIdentity:()=>({...id}),recoveryConfig:()=>plan.recoveryContent,install:()=>calls.push('install'),restart:()=>calls.push('restart'),active:()=>true,restore:()=>calls.push('restore'),restored:()=>true,health:async(p,recovery)=>{calls.push(recovery?'recovery-health':'candidate-health');if(!recovery)throw Error('candidate failed');return {recoveryReady:true,origin:p.recoveryOrigin};}};return {plan,adapter,calls};}
test('pinned recovery differs from original; full binding and config are mandatory',()=>{const t=fixture();assert.match(t.plan.recoveryContent,/ExecStart=\/node \/measured\/server\/cli.ts \/measured\/dist/);assert.equal(verifyRecoveryBinding(t.plan,{active:'active',root:'/original',exec:'/node /original/server/cli.ts /original/dist',content:t.plan.recoveryContent}),false);assert.equal(verifyRecoveryBinding(t.plan,{active:'active',root:'/measured',exec:'/wrong',content:t.plan.recoveryContent}),false);assert.equal(verifyRecoveryBinding(t.plan,{active:'active',root:'/measured',exec:'/node /measured/server/cli.ts /measured/dist',content:t.plan.recoveryContent}),true);});
test('candidate failure restores only explicit measured binding',async()=>{const t=fixture();const result=await switchViewer(t.plan,{adapter:t.adapter});assert.equal(result.rollbackVerified,true);assert.equal(result.state,'rolled-back');assert.equal(t.calls.filter(c=>c==='restore').length,1);});
test('missing explicit recovery cannot mutate or report rollback',async()=>{const t=fixture();delete t.plan.recoveryRoot;await assert.rejects(switchViewer(t.plan,{adapter:t.adapter}));assert.ok(!t.calls.includes('install'));await assert.rejects(rollbackViewer(t.plan,{adapter:t.adapter}));assert.ok(!t.calls.includes('restore'));});
test('awaited checkpoint or health recovery mutations refuse before install',async()=>{for(const phase of ['checkpoint','health']){const t=fixture();let mutated=false;t.adapter.recoveryIdentity=()=>({...id,...(mutated?{assetHash:'e'.repeat(64)}:{})});if(phase==='health')t.adapter.health=async()=>{mutated=true;return {recoveryReady:true};};await assert.rejects(switchViewer(t.plan,{adapter:t.adapter,checkpoint:async()=>{await Promise.resolve();mutated=true;}}));assert.ok(!t.calls.includes('install'));}});
test('recovery drift before restoration or after awaited restore health stays unknown',async()=>{for(const phase of ['before','after']){const t=fixture();let drift=false;t.adapter.recoveryIdentity=()=>({...id,...(drift?{sourceHash:'e'.repeat(64)}:{})});t.adapter.health=async(_p,recovery)=>{if(!recovery){if(phase==='before')drift=true;throw Error('fail');}if(t.calls.includes('restore')&&phase==='after')drift=true;return {recoveryReady:true};};const result=await switchViewer(t.plan,{adapter:t.adapter});assert.equal(result.rollbackVerified,false);assert.equal(result.changed,null);if(phase==='before')assert.ok(!t.calls.includes('restore'));}});
test('config drift and incorrect restored ExecStart cannot verify rollback',async()=>{const t=fixture();t.adapter.restored=()=>false;assert.equal((await switchViewer(t.plan,{adapter:t.adapter})).rollbackVerified,false);const u=fixture();u.adapter.recoveryConfig=()=>u.calls.includes('install')?'changed':u.plan.recoveryContent;assert.equal((await switchViewer(u.plan,{adapter:u.adapter})).rollbackVerified,false);});
test('idempotent candidate and explicit rollback still revalidate recovery',async()=>{const t=fixture();t.plan.ownPrevious={content:t.plan.content};t.adapter.health=async()=>({viewerReady:true,recoveryReady:true});assert.equal((await switchViewer(t.plan,{adapter:t.adapter})).state,'already-active');const u=fixture();assert.equal((await rollbackViewer(u.plan,{adapter:u.adapter})).rollbackVerified,true);});
test('recovery switch pins the original absolute policy storage and rejects missing storage',()=>{
 assert.match(renderRecoverySwitch({root:'/measured',node:'/node',policyPath:'/original/policy.json'}),/ARMIS_OWNER_POLICY_PATH=\/original\/policy.json/);
 assert.throws(()=>renderRecoverySwitch({root:'/measured',node:'/node'}));
});
test('resolved negative readiness cannot authorize install or verified recovery',async()=>{
 const baseline=fixture();baseline.adapter.health=async()=>({recoveryReady:false});await assert.rejects(switchViewer(baseline.plan,{adapter:baseline.adapter}));assert.ok(!baseline.calls.includes('install'));
 const candidate=fixture();candidate.adapter.health=async(_p,recovery)=>({recoveryReady:recovery,viewerReady:false});assert.equal((await switchViewer(candidate.plan,{adapter:candidate.adapter})).state,'rolled-back');
 const restore=fixture();restore.adapter.health=async(_p,recovery)=>{if(!recovery)throw Error('candidate failed');return {recoveryReady:!restore.calls.includes('restore')};};assert.equal((await switchViewer(restore.plan,{adapter:restore.adapter})).rollbackVerified,false);
 const explicit=fixture();explicit.adapter.health=async()=>({recoveryReady:false});await assert.rejects(rollbackViewer(explicit.plan,{adapter:explicit.adapter}));
});
test('binding drift during awaited health cannot become activated or verified rollback',async()=>{
 const candidate=fixture();let bound=true;candidate.adapter.active=()=>bound;candidate.adapter.health=async(_p,recovery)=>{if(!recovery)bound=false;return recovery?{recoveryReady:true}:{viewerReady:true};};
 assert.notEqual((await switchViewer(candidate.plan,{adapter:candidate.adapter})).state,'activated');
 const restore=fixture();let restored=true;restore.adapter.restored=()=>restored;restore.adapter.health=async(_p,recovery)=>{if(!recovery)throw Error('fail');if(restore.calls.includes('restore'))restored=false;return {recoveryReady:true};};
 assert.equal((await switchViewer(restore.plan,{adapter:restore.adapter})).rollbackVerified,false);
});
