import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { OwnerPolicy } from '../server/owner-policy.mjs';
const covered=['owner-chat','executives','workers','delegations','schedules','retries','provider-adapters','tool-processes'];
const fake={capabilities:async()=>({verified:true,covered,chat:true,recipient:'Fake fixture'}),policy:async()=>({applied:true}),cancel:async()=>({stopped:true,residualUsage:false})};
function setup(executor=fake){const dir=mkdtempSync(join(tmpdir(),'armis-policy-'));return {dir,path:join(dir,'policy.json'),policy:new OwnerPolicy(join(dir,'policy.json'),executor)};}
const cmd=(type,businessId='uditus',extras={})=>({id:crypto.randomUUID(),type,businessId,expectedRevision:0,expiresAt:Date.now()+60000,...extras});
test('shutdown fences admissions, survives restart, and cannot replay a changed command',async()=>{const {dir,path,policy}=setup();try{policy.reserve({id:'job1',businessId:'uditus',provider:'fixture'});const command=cmd('company.stop');const receipt=await policy.command(command);assert.equal(receipt.state,'effective');assert.equal(policy.state.companies.uditus.lifecycle,'stopped');assert.throws(()=>policy.reserve({id:'job2',businessId:'uditus',provider:'fixture'}),/holds/);const restarted=new OwnerPolicy(path,fake);assert.equal(restarted.state.companies.uditus.lifecycle,'stopped');assert.equal((await restarted.command(command)).state,'effective');await assert.rejects(restarted.command({...command,type:'company.resume'}),/reused/);}finally{rmSync(dir,{recursive:true});}});
test('partial cancellation remains stopping, failed policy acknowledgment never means effective',async()=>{const {dir,policy}=setup({...fake,cancel:async()=>({stopped:false,residualUsage:true})});try{policy.reserve({id:'job1',businessId:'uditus',provider:'fixture'});const receipt=await policy.command(cmd('company.stop'));assert.equal(receipt.state,'acknowledged');assert.match(receipt.reason,/Cancellation incomplete/);assert.equal(policy.state.companies.uditus.lifecycle,'stopping');assert.equal(policy.state.reservations.length,1);}finally{rmSync(dir,{recursive:true});}});
test('missing coverage fails closed; expiry/revision/allocation validation and Uditus serialization',async()=>{const {dir,policy}=setup(null);try{assert.equal((await policy.view()).capabilities.companyControl,false);assert.equal((await policy.command(cmd('company.stop'))).state,'rejected');await assert.rejects(policy.command(cmd('global.stop',undefined,{expiresAt:0})),/expired/);policy.executor=fake;await assert.rejects(policy.command(cmd('allocation.set','uditus',{allocation:{weight:20,maxConcurrent:2}})),/serialized/);policy.reserve({id:'one',businessId:'uditus',provider:'fixture'});assert.throws(()=>policy.reserve({id:'two',businessId:'uditus',provider:'fixture'}),/holds/);assert.equal(policy.reserve({id:'one',businessId:'uditus',provider:'fixture'}).id,'one');await assert.rejects(policy.command(cmd('company.pause','uditus',{expectedRevision:99})),/conflict/);}finally{rmSync(dir,{recursive:true});}});
test('atomic token/request/spend reservations retain consumption after release and restart',async()=>{const {dir,path,policy}=setup();try{await policy.command(cmd('allocation.set','etsy-studio',{allocation:{weight:25,maxConcurrent:3,tokenLimit:100,requestLimit:2,spendLimitMicros:50}}));policy.reserve({id:'a',businessId:'etsy-studio',provider:'fixture',tokens:60,costMicros:30});assert.throws(()=>policy.reserve({id:'b',businessId:'etsy-studio',provider:'fixture',tokens:50,costMicros:10}),/bound/);policy.release('a',{tokens:60,costMicros:30});const restarted=new OwnerPolicy(path,fake);assert.equal(restarted.state.companies['etsy-studio'].consumedTokens,60);assert.throws(()=>restarted.reserve({id:'b',businessId:'etsy-studio',provider:'fixture',tokens:20,costMicros:30}),/bound/);restarted.reserve({id:'b',businessId:'etsy-studio',provider:'fixture',tokens:20,costMicros:10});restarted.release('b');assert.throws(()=>restarted.reserve({id:'c',businessId:'etsy-studio',provider:'fixture',tokens:1,costMicros:1}),/bound/);}finally{rmSync(dir,{recursive:true});}});
test('global resume restores buildings; rejected edits are atomic and provider routes enforced',async()=>{const {dir,policy}=setup();try{policy.reserve({id:'running',businessId:'uditus',provider:'fixture',tokens:25,costMicros:10});await policy.command(cmd('global.stop'));assert.equal(policy.state.companies.uditus.consumedTokens,25);assert.equal(policy.state.companies.uditus.usageProvenance,'reservation_upper_bound');await policy.command(cmd('global.resume',undefined,{expectedRevision:1}));assert.equal(policy.state.companies.uditus.lifecycle,'running');assert.equal(policy.state.globalStopped,false);await assert.rejects(policy.command(cmd('allocation.set','uditus',{expectedRevision:2,allocation:{weight:99,maxConcurrent:1,tokenLimit:-1}})),/bound/);assert.equal(policy.state.companies.uditus.weight,25);await policy.command(cmd('allocation.set','uditus',{expectedRevision:2,allocation:{weight:25,maxConcurrent:1,allowedProviders:['allowed']}}));assert.throws(()=>policy.reserve({id:'forbidden',businessId:'uditus',provider:'other'}),/forbidden/);policy.reserve({id:'allowed',businessId:'uditus',provider:'allowed'});}finally{rmSync(dir,{recursive:true});}});
